function GARCH_vine_returns = garch_model(vine_returns)
% GARCH_vine_returns = modelTimeSeries(vine_returns)
% returns an estimated model. This code recreates the estimated model
% produced in the Econometric Modeler app. Use the code below to estimate
% the same model, or estimate a model with the same parameters on a new set
% of data.
%
%	Input:
%		vine_returns: A numeric matrix with the same number of columns as the data imported into the app
%
%	Output:
%		GARCH_vine_returns: The model containing estimated parameters
%
% Auto-generated by MATLAB Version 9.4 (R2018a) and Econometrics Toolbox Version 5.0 on 30-Apr-2023 16:54:32
%% Estimate a GARCH Model of time series vine_returns
GARCH_vine_returns = garch('Offset',0,'GARCHLags',1,'ARCHLags',1,'Distribution','t');
GARCH_vine_returns = estimate(GARCH_vine_returns,vine_returns,'Display','off');

end